### ISSUE TITLE
comments completely gray 

### ISSUE THREAD

**Issue by PieterBenjamin** [evturn/cosmic-barf#1]
Comments in my *.sml and *.rb files are effectively impossible to read:
<img width="988" alt="screen shot 2019-03-07 at 10 54 45 am" src="https://user-images.githubusercontent.com/19309215/53981473-752c0700-40c7-11e9-886d-3fbf219c2f38.png">

**Comment by PieterBenjamin** [comment]
I realize this is not an issue with the comments but with the background of the vim buffer which is not being changed from the dark black i have it set as

**Comment by evturn** [comment]
> I realize this is not an issue with the comments but with the background of the vim buffer which is not being changed from the dark black i have it set as

Thanks for pointing that out. 79499b1 has an update for that.
